# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b3dbc4c91f99ea6c9a4e0194eddfcee"
name = "Shark-Voice-AI"
handle = "shark-voice-ai"
application_url = "https://keyboard-adware-celtic-nature.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = ["https://keyboard-adware-celtic-nature.trycloudflare.com/auth/callback", "https://keyboard-adware-celtic-nature.trycloudflare.com/auth/shopify/callback", "https://keyboard-adware-celtic-nature.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
